name: "Tetra test"
on:
  push:
    branches:
      - main
jobs:
  api:
    runs-on: ubuntu-20.04
    environment: test
    env:
      cwd: api
    defaults:
      run:
        working-directory: ${{ env.cwd }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: "oracle"

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.9.2

      - name: Init env variables
        run: |
          echo SPRING_DATASOURCE_URL=${{secrets.SPRING_DATASOURCE_URL}} >> "$GITHUB_ENV"
          echo SPRING_DATASOURCE_USERNAME=${{secrets.SPRING_DATASOURCE_USERNAME}} >> "$GITHUB_ENV"
          echo SPRING_DATASOURCE_PASSWORD=${{secrets.SPRING_DATASOURCE_PASSWORD}} >> "$GITHUB_ENV"
          echo SPRING_MAIL_HOST=${{secrets.SPRING_MAIL_HOST}} >> "$GITHUB_ENV"
          echo SPRING_MAIL_PASSWORD=${{secrets.SPRING_MAIL_PASSWORD}} >> "$GITHUB_ENV"
          echo SPRING_MAIL_PORT=${{secrets.SPRING_MAIL_PORT}} >> "$GITHUB_ENV"
          echo SPRING_MAIL_USERNAME=${{secrets.SPRING_MAIL_USERNAME}} >> "$GITHUB_ENV"
          echo SPRING_PROFILES_ACTIVE=${{secrets.SPRING_PROFILES_ACTIVE}} >> "$GITHUB_ENV"

      - name: Start mysql server
        run: |
          sudo /etc/init.d/mysql start
          mysql -e 'CREATE DATABASE ${{ secrets.DB_DATABASE }};' -h 127.0.0.1 -u${{secrets.SPRING_DATASOURCE_USERNAME}} -p${{ secrets.SPRING_DATASOURCE_PASSWORD }}

      - run: mvn clean test
